apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data: 
  db-password: YW5nZWxna2U=

# Base64 of angelgke
# https://www.base64encode.org/
# Base64 of angelgke is YW5nZWxna2U=