apiVersion: apps/v1
kind: Deployment  
metadata: # Dictionary
  name: myapp3-deployment
spec: # Dictionary
  replicas: 3
  selector: 
    matchLabels: 
      app: myapp3
  template:
    metadata: # Dictionary
      name: myapp3-pod
      labels:
        app: myapp3 # Key Value Pairs   
    spec:
      containers: # List
        - name: myapp3-container
          image: us-central1-docker.pkg.dev/laboratorio-oct-devoteam/angelgke/webpage:449af98
          ports: 
            - containerPort: 80          